### PR TITLE
fix responsive layout

### PR DESCRIPTION
**Pull request by dnextreme88**
- Added posted date container, getting current date.
- Fixed responsive layout.

### CODE REVIEW

**Comment by dons20** [comment]
Hey there, thanks for submitting a PR. Could you share a screenshot / video of the changes you did in action? It will help me to better review the changes overall.

**Comment by dnextreme88** [comment]
Hey Keno,

Didn't realize you would reply so early after submitting a PR, my apologies. I found your repo a huge relief on making a Steam review a breeze and decided to check it out. Found a few layout bugs for XL viewports. Kindly see attached for the changes. Thank you!

Sincerely,
Kevin D. 

    On Wednesday, November 29, 2023 at 04:57:57 PM GMT+8, Keno Clayton ***@***.***> wrote:  
 
 


Hey there, thanks for submitting a PR. Could you share a screenshot / video of the changes you did in action? It will help me to better review the changes overall.

**Comment by dnextreme88** [comment]
Hey! Apologies for the abrupt PR. Found a layout bug for XL viewport. Kindly see attached for the changes. Thank you!

Original:
steam-review-editor-original

Changed:
steam-review-editor-changes

**Review by dons20 — APPROVED** [review]
LGTM

**Comment by dnextreme88** [comment]
Hey @dons20, I don't think this was deployed yet, last deployment mentioned 5 years ago. I just stumbled upon this review editor again and was using it for a review I would be submitting but realized the changes weren't reflected yet.

**Comment by dons20** [comment]
@dnextreme88 Should be visible now, I don't recall what deploy process I had in place at that time, but for now I just synced the changes with my gh-pages branch and it deployed automatically.

**Pull request merged**
