### PR TITLE
UI updates

### PR DESCRIPTION
**Pull request by dnextreme88**
Issue #19

- Add `[h2][/h2]`, `[h3][/h3]`, and `[hr][/hr]` tags
- Add mobile styles
- Fix styles of `[spoiler][/spoiler]` tag
- Fix preview of `[list][/list] tag on its respective container
- Refactor preview of `[quote=author][/quote]` tag
- Refactor styles to somewhat closely resemble the current Steam reviews

### CODE REVIEW

**Comment by dons20** [comment]
Thanks for the help! I'll preview this locally and merge it later today. Should be able to deploy it tonight if no issues are found

**Comment by dons20** [comment]
Looks good in my tests. I will be pushing some additional bugfixes before releasing.

**Comment by dnextreme88** [comment]
Wow, that was quick! Thank you very much. Glad to be of help

**Comment by dnextreme88** [comment]
Wouldn't it be nice to also include a feature to let users pick if they recommend the game or not? Then display the appropriate thumbs up/down icon on the markup preview as well. Just a thought.

**Comment by dons20** [comment]
Funny enough, I added that in my rework branch when I was testing an update. It will be part of the code for sure.

**Pull request merged**
